const db = window.supabase.createClient('https://mpxywnmxifiuqixmxdri.supabase.co', 'sb_publishable_i6r_dD6DwdpYHSXUIvU4Kw_EWz5qwGI');
if(window.pdfjsLib){window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';}
let session = null; let activeProject = null;
const $ = selector => document.querySelector(selector);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),3000);}
function showWorkspace(){ $('#auth-gate').hidden=true; $('#workspace').hidden=false; $('#session-controls').innerHTML=`<span class="signed-in-label">${session.user.email}</span><button class="avatar" id="signout">↗</button>`;$('#signout').onclick=async()=>{await db.auth.signOut();location.reload();};loadProjects(); }
async function loadProjects(){const {data,error}=await db.from('projects').select('*').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(error){toast(error.message);return;}const list=$('#project-list');list.innerHTML=data.length?data.map(p=>`<button class="project-card" data-id="${p.id}"><span class="eyebrow">Project workspace</span><h2>${p.name}</h2><p>${p.address||'Address not added'} · ${p.description||'No description yet'}</p><span class="project-arrow">Open project →</span></button>`).join(''):`<div class="empty-projects"><h2>No projects yet</h2><p>Create a project workspace and upload documents to begin.</p></div>`;list.querySelectorAll('[data-id]').forEach(card=>card.onclick=()=>openProject(data.find(p=>p.id===card.dataset.id)));}
function openProject(project){activeProject=project;$('#project-list').hidden=true;$('#new-project-button').hidden=true;$('#project-view').hidden=false;$('#project-title').textContent=project.name;$('#project-meta').textContent=`${project.address||'Address not added'} · ${project.description||'No description yet'}`;loadDocuments();}
async function loadDocuments(){const {data,error}=await db.from('documents').select('*').eq('project_id',activeProject.id).order('created_at',{ascending:false});if(error){toast(error.message);return;}$('#file-count').textContent=data.length;$('#file-list').innerHTML=data.length?data.map(file=>`<div class="file-item"><span class="file-icon">PDF</span><div><strong>${file.file_name}</strong><span>Uploaded document · ${(file.file_size/1024/1024).toFixed(1)} MB</span></div></div>`).join(''):`<div class="empty-state compact"><h2>No documents uploaded</h2><p>Add your project PDFs to start.</p></div>`;}
$('#auth-form').onsubmit=async e=>{e.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:$('#auth-email').value,password:$('#auth-password').value});if(error){$('#auth-message').textContent=error.message;return;}session=data.session;showWorkspace();};$('#signup-button').onclick=async()=>{const {data,error}=await db.auth.signUp({email:$('#auth-email').value,password:$('#auth-password').value});if(error){$('#auth-message').textContent=error.message;return;}if(data.session){session=data.session;showWorkspace();}else{$('#auth-message').textContent='Account created. You can now sign in.';}};
$('#new-project-button').onclick=()=>{$('#modal').hidden=false;};$('#close-modal').onclick=()=>{$('#modal').hidden=true;};$('#back-to-projects').onclick=()=>{activeProject=null;$('#project-view').hidden=true;$('#project-list').hidden=false;$('#new-project-button').hidden=false;loadProjects();};
$('#project-form').onsubmit=async e=>{e.preventDefault();const {data,error}=await db.from('projects').insert({name:$('#project-name').value,address:$('#project-address').value,description:$('#project-description').value,project_type:'Architecture',location:$('#project-address').value,owner_id:session.user.id,floor_area_m2:1,completion_year:new Date().getFullYear(),cost_per_m2:0}).select().single();if(error){$('#project-message').textContent=error.message;return;}$('#modal').hidden=true;e.target.reset();openProject(data);toast('Project workspace created');};
$('#file-upload').onchange=async e=>{if(!activeProject)return;const uploaded=[...e.target.files];for(const file of uploaded){const {error}=await db.from('documents').insert({project_id:activeProject.id,owner_id:session.user.id,file_name:file.name,file_type:file.type||'application/pdf',file_size:file.size});if(error){toast(error.message);return;}}await loadDocuments();toast(`${uploaded.length} document${uploaded.length===1?'':'s'} added`);};$('#run-check').onclick=()=>{$('[data-section="check"]').click();toast('Project check will run once document analysis is connected');};document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active-panel'));$(`#${tab.dataset.section}`).classList.add('active-panel');});
$('#reset-button').onclick=async()=>{const email=$('#auth-email').value;if(!email){$('#auth-message').textContent='Enter your email first.';return;}const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin});$('#auth-message').textContent=error?error.message:'Password reset email sent. Check your inbox or spam folder.';};
async function readPdf(file){if(!window.pdfjsLib)throw new Error('PDF reader did not load. Refresh the page and try again.');const bytes=await file.arrayBuffer();const pdf=await window.pdfjsLib.getDocument({data:bytes}).promise;let text='';for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber);const viewport=page.getViewport({scale:1.5});const content=await page.getTextContent();text+=content.items.map(item=>item.str).join(' ')+'\n';}if(text.trim())return text.trim();if(!window.Tesseract)throw new Error('OCR reader did not load. Refresh the page and try again.');let ocrText='';for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber);const viewport=page.getViewport({scale:1.5});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const result=await window.Tesseract.recognize(canvas,'eng');ocrText+=result.data.text+'\n';}return ocrText.trim();}
db.auth.getSession().then(({data})=>{if(data.session){session=data.session;showWorkspace();}});

async function readPdf(file){if(!window.pdfjsLib)throw new Error('PDF reader did not load. Refresh the page and try again.');const bytes=await file.arrayBuffer();const pdf=await window.pdfjsLib.getDocument({data:bytes}).promise;let text='';for(let page=1;page<=pdf.numPages;page++){const content=await (await pdf.getPage(page)).getTextContent();text+=content.items.map(item=>item.str).join(' ')+'\\n';}return text.trim();}
function renderOverview(files){const combined=files.map(f=>f.extracted_text||'').join(' ');const words=combined.split(/\\s+/).filter(Boolean).length;$('#overview-file-count').textContent=files.length;$('#overview-title').textContent=files.length?(files.length+' document'+(files.length===1?'':'s')+' read for '+activeProject.name+'.'):'Upload project documents to build an overview.';$('#overview-summary').textContent=files.length?('Docsifter found approximately '+words.toLocaleString()+' words across the project files. Review the source documents and use search to find specific information.'):'Docsifter will summarise the information found in your uploaded files.';$('#overview-facts').innerHTML=files.length?('<span>'+words.toLocaleString()+' words</span><span>'+files.length+' source file'+(files.length===1?'':'s')+'</span>'):'';}
function renderSearch(files,query){const results=$('#search-results');if(!query){results.innerHTML='<p class="empty-search">Search results will appear here.</p>';return;}const q=query.toLowerCase();const matches=[];files.forEach(file=>{const text=file.extracted_text||'';const index=text.toLowerCase().indexOf(q);if(index>=0){const start=Math.max(0,index-100),end=Math.min(text.length,index+q.length+180);matches.push('<div class="search-result"><span class="file-icon">PDF</span><span><strong>'+file.file_name+'</strong><small>'+text.slice(start,end)+'</small></span></div>');}});results.innerHTML=matches.length?matches.join(''):'<p class="empty-search">No matching text found in the uploaded files.</p>';}
async function loadDocuments(){const {data,error}=await db.from('documents').select('*').eq('project_id',activeProject.id).order('created_at',{ascending:false});if(error){toast(error.message);return;}$('#file-count').textContent=data.length;$('#file-list').innerHTML=data.length?data.map(file=>'<div class="file-item"><span class="file-icon">PDF</span><div><strong>'+file.file_name+'</strong><span>Document read · '+(file.file_size/1024/1024).toFixed(1)+' MB</span></div></div>').join(''):'<div class="empty-state compact"><h2>No documents uploaded</h2><p>Add your project PDFs to start.</p></div>';renderOverview(data);window.currentDocs=data;}
$('#file-upload').onchange=async e=>{if(!activeProject)return;const uploaded=[...e.target.files];for(const file of uploaded){try{const extracted_text=await readPdf(file);if(!extracted_text)throw new Error('This PDF has no selectable text. Scanned drawings need OCR, which is not included yet.');const {error}=await db.from('documents').insert({project_id:activeProject.id,owner_id:session.user.id,file_name:file.name,file_type:file.type||'application/pdf',file_size:file.size,extracted_text});if(error)throw error;}catch(error){toast('Could not read '+file.name+': '+(error.message||'PDF error'));return;}}await loadDocuments();toast(uploaded.length+' document'+(uploaded.length===1?'':'s')+' read and searchable');e.target.value='';};
$('#document-search').oninput=e=>renderSearch(window.currentDocs||[],e.target.value);
