const db = window.supabase.createClient('https://mpxywnmxifiuqixmxdri.supabase.co', 'sb_publishable_i6r_dD6DwdpYHSXUIvU4Kw_EWz5qwGI');
let session = null; let activeProject = null;
const $ = selector => document.querySelector(selector);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),3000);}
function showWorkspace(){ $('#auth-gate').hidden=true; $('#workspace').hidden=false; $('#session-controls').innerHTML=`<span class="signed-in-label">${session.user.email}</span><button class="avatar" id="signout">↗</button>`;$('#signout').onclick=async()=>{await db.auth.signOut();location.reload();};loadProjects(); }
async function loadProjects(){const {data,error}=await db.from('projects').select('*').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(error){toast(error.message);return;}const list=$('#project-list');list.innerHTML=data.length?data.map(p=>`<button class="project-card" data-id="${p.id}"><span class="eyebrow">Project workspace</span><h2>${p.name}</h2><p>${p.address||'Address not added'} · ${p.description||'No description yet'}</p><span class="project-arrow">Open project →</span></button>`).join(''):`<div class="empty-projects"><h2>No projects yet</h2><p>Create a project workspace and upload documents to begin.</p></div>`;list.querySelectorAll('[data-id]').forEach(card=>card.onclick=()=>openProject(data.find(p=>p.id===card.dataset.id)));}
function openProject(project){activeProject=project;$('#project-list').hidden=true;$('#new-project-button').hidden=true;$('#project-view').hidden=false;$('#project-title').textContent=project.name;$('#project-meta').textContent=`${project.address||'Address not added'} · ${project.description||'No description yet'}`;loadDocuments();}
async function loadDocuments(){const {data,error}=await db.from('documents').select('*').eq('project_id',activeProject.id).order('created_at',{ascending:false});if(error){toast(error.message);return;}$('#file-count').textContent=data.length;$('#file-list').innerHTML=data.length?data.map(file=>`<div class="file-item"><span class="file-icon">PDF</span><div><strong>${file.file_name}</strong><span>Uploaded document · ${(file.file_size/1024/1024).toFixed(1)} MB</span></div></div>`).join(''):`<div class="empty-state compact"><h2>No documents uploaded</h2><p>Add your project PDFs to start.</p></div>`;}
$('#auth-form').onsubmit=async e=>{e.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:$('#auth-email').value,password:$('#auth-password').value});if(error){$('#auth-message').textContent=error.message;return;}session=data.session;showWorkspace();};$('#signup-button').onclick=async()=>{const {data,error}=await db.auth.signUp({email:$('#auth-email').value,password:$('#auth-password').value});if(error){$('#auth-message').textContent=error.message;return;}if(data.session){session=data.session;showWorkspace();}else{$('#auth-message').textContent='Account created. You can now sign in.';}};
$('#new-project-button').onclick=()=>{$('#modal').hidden=false;};$('#close-modal').onclick=()=>{$('#modal').hidden=true;};$('#back-to-projects').onclick=()=>{activeProject=null;$('#project-view').hidden=true;$('#project-list').hidden=false;$('#new-project-button').hidden=false;loadProjects();};
$('#project-form').onsubmit=async e=>{e.preventDefault();const {data,error}=await db.from('projects').insert({name:$('#project-name').value,address:$('#project-address').value,description:$('#project-description').value,project_type:'Architecture',location:$('#project-address').value,owner_id:session.user.id,floor_area_m2:1,completion_year:new Date().getFullYear(),cost_per_m2:0}).select().single();if(error){$('#project-message').textContent=error.message;return;}$('#modal').hidden=true;e.target.reset();openProject(data);toast('Project workspace created');};
$('#file-upload').onchange=async e=>{if(!activeProject)return;const uploaded=[...e.target.files];for(const file of uploaded){const {error}=await db.from('documents').insert({project_id:activeProject.id,owner_id:session.user.id,file_name:file.name,file_type:file.type||'application/pdf',file_size:file.size});if(error){toast(error.message);return;}}await loadDocuments();toast(`${uploaded.length} document${uploaded.length===1?'':'s'} added`);};$('#run-check').onclick=()=>{$('[data-section="check"]').click();toast('Project check will run once document analysis is connected');};document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active-panel'));$(`#${tab.dataset.section}`).classList.add('active-panel');});
db.auth.getSession().then(({data})=>{if(data.session){session=data.session;showWorkspace();}});
